name: altran-olimex-gadget 
version: '0.1' 
summary: u-boot bootloader for olimex lime2 board
description: |
      Bootloader files and partitoning data to create a
      bootable Ubuntu Core image for the olimex lime2 board
type: gadget
architectures:
        - build-on: amd64
          run-on: armhf
grade: devel 
confinement: devmode 

parts:
  uboot: 
    source: https://git.denx.de/u-boot.git
    #    source-branch: v2017.11-rc4
    source-branch: v2018.05
    plugin: nil
    #    artifacts: [u-boot-sunxi-with-spl.bin]
    prepare: |
        patch -p1 < ../../../uboot.patch
        make A20-OLinuXino-Lime2_defconfig 
    build: |
        CROSS_COMPILE=arm-linux-gnueabi- make
    install: |
        cp u-boot-sunxi-with-spl.bin $SNAPCRAFT_PART_INSTALL/
        tools/mkenvimage -r -s 131072 -o $SNAPCRAFT_PART_INSTALL/uboot.env ../../../uboot.env.in
        cd $SNAPCRAFT_PART_INSTALL/; ln -s uboot.env uboot.conf
    build-packages:
        - libpython2.7-dev
        - build-essential
        - bc
        - gcc-arm-linux-gnueabi  
